# Generated by Django 4.2.7 on 2025-09-14 11:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the method", max_length=100
                    ),
                ),
                (
                    "external_method_id",
                    models.CharField(
                        blank=True, help_text="External method ID", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payments_payment_method",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="payments_pa_user_id_e03dcf_idx",
                    ),
                    models.Index(
                        fields=["method_type"], name="payments_pa_method__656c5b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        help_text="External payment ID", max_length=100, unique=True
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("session_fee", "Session Fee"),
                            ("platform_fee", "Platform Fee"),
                            ("referral_fee", "Referral Fee"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in GBP", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_payment_id",
                    models.CharField(
                        blank=True, help_text="Stripe payment ID", max_length=100
                    ),
                ),
                (
                    "external_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="External service fee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="referrals.referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments_payment",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
                    ),
                    models.Index(
                        fields=["payment_type"], name="payments_pa_payment_09c1c1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_pa_created_b8a300_idx"
                    ),
                ],
            },
        ),
    ]
