# Generated by Django 4.2.7 on 2025-09-14 11:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("referral_update", "Referral Update"),
                            ("matching_complete", "Matching Complete"),
                            ("invitation", "Invitation"),
                            ("response", "Response"),
                            ("appointment", "Appointment"),
                            ("system", "System"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("message_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "inbox_notification_template",
                "indexes": [
                    models.Index(
                        fields=["notification_type"],
                        name="inbox_notif_notific_e353c8_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="inbox_notif_is_acti_e0e4b2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("referral_update", "Referral Update"),
                            ("matching_complete", "Matching Complete"),
                            ("invitation", "Invitation"),
                            ("response", "Response"),
                            ("appointment", "Appointment"),
                            ("system", "System"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="referrals.appointment",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="referrals.candidate",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="referrals.referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "inbox_notification",
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="inbox_notif_user_id_5aa4a7_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="inbox_notif_notific_9107af_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="inbox_notif_priorit_1c661c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inbox_notif_created_b9237d_idx"
                    ),
                ],
            },
        ),
    ]
