# Generated by Django 4.2.7 on 2025-09-20 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='email_body_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='email_subject_template',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_update_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='in_app', max_length=10)),
                ('matching_complete_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='in_app', max_length=10)),
                ('invitation_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='all', max_length=10)),
                ('response_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='in_app', max_length=10)),
                ('appointment_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='all', max_length=10)),
                ('system_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='in_app', max_length=10)),
                ('reminder_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('push', 'Push Notification'), ('all', 'All Methods'), ('none', 'Disabled')], default='email', max_length=10)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'inbox_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'db_table': 'inbox_notification_channel',
                'indexes': [models.Index(fields=['user', 'is_active'], name='inbox_notif_user_id_a9bdd4_idx'), models.Index(fields=['channel_name'], name='inbox_notif_channel_90f7f6_idx')],
            },
        ),
    ]
