services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: referwell
      POSTGRES_USER: referwell
      POSTGRES_PASSWORD: referwell
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U referwell -d referwell"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    environment:
      - MAILCATCHER_IP=0.0.0.0

volumes:
  postgres_data:
  redis_data:
