# Generated by Django 4.2.7 on 2025-09-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("matching", "Matching"),
                    ("shortlisted", "Shortlisted"),
                    ("high_touch_queue", "High-Touch Queue"),
                    ("invited", "Invited"),
                    ("responded", "Responded"),
                    ("appointment_booked", "Appointment Booked"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
