# Generated by Django 4.2.7 on 2025-09-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0002_add_high_touch_queue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="condition_description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the condition"
            ),
        ),
    ]
