# Generated by Django 4.2.7 on 2025-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0003_referral_condition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referral_id",
            field=models.CharField(
                help_text="Human-readable referral ID", max_length=30, unique=True
            ),
        ),
    ]
