# Generated by Django 4.2.7 on 2025-09-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0004_alter_referral_referral_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="language_requirements",
            field=models.JSONField(
                blank=True, default=list, help_text="List of language requirements"
            ),
        ),
    ]
