# Generated by Django 4.2.7 on 2025-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0005_referral_language_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="patient_age_group",
            field=models.CharField(
                blank=True, help_text="Patient age group", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="routing_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Metadata for routing decisions"
            ),
        ),
    ]
