# Generated by Django 4.2.7 on 2025-09-14 18:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("profile_setup", "Profile Setup"),
                            ("organisation_setup", "Organisation Setup"),
                            ("preferences", "Preferences"),
                            ("verification", "Verification"),
                            ("completion", "Completion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("gp", "GP"),
                            ("patient", "Patient"),
                            ("psychologist", "Psychologist"),
                            ("admin", "Admin"),
                            ("high_touch_referrer", "High-Touch Referrer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("help_text", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Onboarding Step",
                "verbose_name_plural": "Onboarding Steps",
                "db_table": "accounts_onboarding_step",
                "ordering": ["user_type", "order"],
                "unique_together": {("user_type", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserOnboardingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step-specific data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="accounts.onboardingstep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Onboarding Progress",
                "verbose_name_plural": "User Onboarding Progress",
                "db_table": "accounts_user_onboarding_progress",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="accounts_us_user_id_15b143_idx"
                    ),
                    models.Index(
                        fields=["step", "status"], name="accounts_us_step_id_ae7dd1_idx"
                    ),
                ],
                "unique_together": {("user", "step")},
            },
        ),
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "session_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Session-wide data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.onboardingstep",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Session",
                "verbose_name_plural": "Onboarding Sessions",
                "db_table": "accounts_onboarding_session",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="accounts_on_user_id_b0f222_idx"
                    ),
                    models.Index(
                        fields=["status"], name="accounts_on_status_f7c2a8_idx"
                    ),
                ],
            },
        ),
    ]
