# Generated by Django 4.2.7 on 2025-09-14 20:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_onboardingstep_useronboardingprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
