# Generated by Django 4.2.7 on 2025-10-02 18:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0007_alter_referral_patient_patientprofile_and_more"),
        ("accounts", "0004_organisation_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vetted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about verification decision"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type__in": ["gp", "psychologist"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vetted_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Status",
                "verbose_name_plural": "Verification Statuses",
                "db_table": "accounts_verification_status",
                "indexes": [
                    models.Index(
                        fields=["status"], name="accounts_ve_status_9fb83a_idx"
                    ),
                    models.Index(
                        fields=["vetted_at"], name="accounts_ve_vetted__19c28c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientClaimInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Hashed secure token for patient claim",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send invite to", max_length=254
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_invites",
                        to="referrals.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Claim Invite",
                "verbose_name_plural": "Patient Claim Invites",
                "db_table": "accounts_patient_claim_invite",
                "indexes": [
                    models.Index(fields=["token"], name="accounts_pa_token_a932f0_idx"),
                    models.Index(fields=["email"], name="accounts_pa_email_ad571f_idx"),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_c84e3e_idx"
                    ),
                    models.Index(
                        fields=["used_at"], name="accounts_pa_used_at_6aa423_idx"
                    ),
                ],
            },
        ),
    ]
