# Generated by Django 4.2.7 on 2025-09-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_add_postgis_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="languages",
            field=models.JSONField(default=list, help_text="Languages spoken"),
        ),
    ]
