# Generated by Django 4.2.7 on 2025-09-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("histogram", "Histogram"),
                            ("summary", "Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("value", models.FloatField(help_text="Current value of the metric")),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=dict, help_text="Metric labels"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "db_table": "ops_metric",
                "indexes": [
                    models.Index(fields=["name"], name="ops_metric_name_916865_idx"),
                    models.Index(
                        fields=["metric_type"], name="ops_metric_metric__311211_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="ops_metric_updated_1382b7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "logger_name",
                    models.CharField(help_text="Name of the logger", max_length=100),
                ),
                ("message", models.TextField(help_text="Log message")),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional log details"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, help_text="Request ID for tracing", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "db_table": "ops_system_log",
                "indexes": [
                    models.Index(fields=["level"], name="ops_system__level_c0fbcb_idx"),
                    models.Index(
                        fields=["logger_name"], name="ops_system__logger__3c21e3_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ops_system__user_id_d1ea25_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ops_system__created_742403_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("referral_submit", "Referral Submit"),
                            ("matching_start", "Matching Start"),
                            ("matching_complete", "Matching Complete"),
                            ("invitation_sent", "Invitation Sent"),
                            ("invitation_response", "Invitation Response"),
                            ("appointment_booked", "Appointment Booked"),
                            ("payment_processed", "Payment Processed"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "object_type",
                    models.CharField(
                        blank=True, help_text="Type of object affected", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="ID of object affected", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the event"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "db_table": "ops_audit_event",
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="ops_audit_e_event_t_2eb142_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ops_audit_e_user_id_7e007e_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="ops_audit_e_object__8774c0_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ops_audit_e_created_274925_idx"
                    ),
                ],
            },
        ),
    ]
