# Generated by Django 4.2.7 on 2025-09-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchingrun",
            name="algorithm_name",
            field=models.CharField(default="Default Algorithm", max_length=100),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="algorithm_version",
            field=models.CharField(default="1.0", max_length=20),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="average_confidence",
            field=models.FloatField(
                blank=True, help_text="Average confidence score", null=True
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="failed_matches",
            field=models.PositiveIntegerField(default=0, help_text="Failed matches"),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata"
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="processing_time_seconds",
            field=models.FloatField(
                blank=True, help_text="Processing time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="successful_matches",
            field=models.PositiveIntegerField(
                default=0, help_text="Successful matches found"
            ),
        ),
        migrations.AddField(
            model_name="matchingrun",
            name="total_referrals",
            field=models.PositiveIntegerField(
                default=0, help_text="Total referrals processed"
            ),
        ),
    ]
