name: Database Operations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  migration-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: referwell_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for migration conflicts
        run: |
          python manage.py makemigrations --check --dry-run --settings=referwell.settings.development
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

      - name: Run migrations
        run: |
          python manage.py migrate --settings=referwell.settings.development
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

      - name: Check migration safety
        run: |
          python manage.py check --deploy --settings=referwell.settings.development
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

  schema-validation:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: referwell_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate --settings=referwell.settings.development
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

      - name: Validate database schema
        run: |
          python manage.py validate --settings=referwell.settings.development
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

      - name: Check PostGIS extensions
        run: |
          python manage.py dbshell --settings=referwell.settings.development -c "SELECT PostGIS_Version();"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test

      - name: Check pgvector extension
        run: |
          python manage.py dbshell --settings=referwell.settings.development -c "SELECT extname FROM pg_extension WHERE extname = 'vector';"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/referwell_test
