name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test --settings=referwell.settings.development
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"

      - name: Build static files
        run: |
          python manage.py collectstatic --noinput --settings=referwell.settings.production

      - name: Create deployment package
        run: |
          tar -czf referwell-direct.tar.gz \
            --exclude='.git' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.pytest_cache' \
            --exclude='.coverage' \
            --exclude='htmlcov' \
            --exclude='.env*' \
            --exclude='logs' \
            --exclude='staticfiles' \
            --exclude='media' \
            .

      - name: Upload deployment package
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: referwell-direct.tar.gz

      # Uncomment and configure for your deployment target
      # - name: Deploy to production
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /path/to/deployment
      #       # Add your deployment commands here
