name: Security Scan

on:
  schedule:
    - cron: "0 2 * * 1" # Run every Monday at 2 AM
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit semgrep

      - name: Run Safety check
        run: |
          safety check --json --output safety-report.json
          safety check

      - name: Run Bandit security scan
        run: |
          bandit -r . -f json -o bandit-report.json
          bandit -r . -ll

      - name: Run Semgrep security scan
        run: |
          semgrep --config=auto --json --output=semgrep-report.json .
          semgrep --config=auto .

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports-${{ github.run_number }}
          path: |
            safety-report.json
            bandit-report.json
            semgrep-report.json

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
